window.GARDEN_PHOTOS = [
  {
    "id": "official-005",
    "image": "images/official-005.jpg",
    "month": 9,
    "day": 14,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.518432689456105,
      "lon": -122.70762675757672,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Sand and Stone Garden",
    "openLicense": false
  },
  {
    "id": "commons_163154368",
    "image": "images/commons_163154368.jpg",
    "month": 7,
    "day": 11,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.51843235641007,
      "lon": -122.70762257937439,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "WLernerPJG",
    "source": "https://commons.wikimedia.org/wiki/File:Sand_and_Stone_Garden.jpg",
    "caption": "Sand and Stone Garden of Portland Japanese Garden",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "official-010",
    "image": "images/official-010.jpg",
    "month": 9,
    "day": 14,
    "location": "Strolling Pond Garden",
    "landmark": "Sapporo Pagoda",
    "point": {
      "lat": 45.518465838446424,
      "lon": -122.70820843780169,
      "name": "Sapporo Pagoda",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Strolling Pond Garden",
    "openLicense": false
  },
  {
    "id": "official-024",
    "image": "images/official-024.jpg",
    "month": 9,
    "day": 14,
    "location": "Entry Garden",
    "landmark": "Antique Gate",
    "point": {
      "lat": 45.5193984975832,
      "lon": -122.70764504597607,
      "name": "Antique Gate",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Entry Garden",
    "openLicense": false
  },
  {
    "id": "official-050",
    "image": "images/official-050.jpg",
    "month": 11,
    "day": 5,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.51842911336225,
      "lon": -122.7076213535673,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Sand and Stone Garden",
    "openLicense": false
  },
  {
    "id": "official-037",
    "image": "images/official-037.jpg",
    "month": 10,
    "day": 29,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.51866334750966,
      "lon": -122.70779580751753,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Flat Garden",
    "openLicense": false
  },
  {
    "id": "commons_163154493",
    "image": "images/commons_163154493.jpg",
    "month": 1,
    "day": 31,
    "location": "Tea Garden",
    "landmark": "Kashintei Tea House approach",
    "point": {
      "lat": 45.51846154356594,
      "lon": -122.70925331060084,
      "name": "Kashintei Tea House approach",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "WLernerPJG",
    "source": "https://commons.wikimedia.org/wiki/File:The_Tea_Garden_of_Portland_Japanese_Garden.jpg",
    "caption": "The Tea Garden of Portland Japanese Garden",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_163154343",
    "image": "images/commons_163154343.jpg",
    "month": 5,
    "day": 9,
    "location": "Natural Garden",
    "landmark": "Stone stairs with azaleas",
    "point": {
      "lat": 45.51823064015338,
      "lon": -122.70740119066335,
      "name": "Stone stairs with azaleas",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "WLernerPJG",
    "source": "https://commons.wikimedia.org/wiki/File:Natural_Garden_in_Portland_Japanese_Garden..jpg",
    "caption": "Natural Garden in Portland Japanese Garden.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_622717",
    "image": "images/commons_622717.jpg",
    "month": 2,
    "day": 15,
    "location": "Strolling Pond Garden",
    "landmark": "Upper pond and laceleaf maple",
    "point": {
      "lat": 45.5188057250345,
      "lon": -122.70879837415758,
      "name": "Upper pond and laceleaf maple",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "EncMstr",
    "source": "https://commons.wikimedia.org/wiki/File:Pdx_washpark_japanesegarden_rightside.jpg",
    "caption": "w:Portland Japanese Garden Winter view",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "openLicense": true
  },
  {
    "id": "official-047",
    "image": "images/official-047.jpg",
    "month": 11,
    "day": 1,
    "location": "Natural Garden",
    "landmark": "Moon Gate",
    "point": {
      "lat": 45.51815748803859,
      "lon": -122.70821131479579,
      "name": "Moon Gate",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Natural Garden",
    "openLicense": false
  },
  {
    "id": "commons_163154391",
    "image": "images/commons_163154391.jpg",
    "month": 4,
    "day": 19,
    "location": "Strolling Pond Garden",
    "landmark": "Upper Pond and Moon Bridge",
    "point": {
      "lat": 45.51878241030227,
      "lon": -122.7089228411676,
      "name": "Upper Pond and Moon Bridge",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "WLernerPJG",
    "source": "https://commons.wikimedia.org/wiki/File:Strolling_Pond_Garden_of_Portland_Japanese_Garden.jpg",
    "caption": "Strolling Pond Garden of Portland Japanese Garden",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_163154684",
    "image": "images/commons_163154684.jpg",
    "month": 5,
    "day": 3,
    "location": "Tsubo-Niwa",
    "landmark": "Courtyard maple",
    "point": {
      "lat": 45.519097597348015,
      "lon": -122.70874080656316,
      "name": "Courtyard maple",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "WLernerPJG",
    "source": "https://commons.wikimedia.org/wiki/File:Tsubo-Niwa_at_Portland_Japanese_Garden.jpg",
    "caption": "Tsubo-Niwa at Portland Japanese Garden",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_12338096",
    "image": "images/commons_12338096.jpg",
    "month": 12,
    "day": 3,
    "location": "Flat Garden",
    "landmark": "Circle and gourd islands",
    "point": {
      "lat": 45.51866261115818,
      "lon": -122.70786468342222,
      "name": "Circle and gourd islands",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Melissa Wilmot",
    "source": "https://commons.wikimedia.org/wiki/File:Flat_Garden.jpg",
    "caption": "Flat Garden at the Portland Japanese Garden",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "openLicense": true
  },
  {
    "id": "flickr_14800652882",
    "image": "images/flickr_14800652882.jpg",
    "month": 7,
    "day": 19,
    "location": "Strolling Pond Garden",
    "landmark": "Upper Pond",
    "point": {
      "lat": 45.51837694438296,
      "lon": -122.70888463795657,
      "name": "Upper Pond",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Paul VanDerWerf",
    "source": "https://www.flickr.com/photos/pavdw/14800652882/",
    "caption": "Upper Pool at the  Portland Japanese Garden.   The Portland Japanese Garden is a traditional Japanese garden occupying 5.5 acres (22,000 m²), located within Washington Park in the west hills of Portland, Oregon, USA.  Three of the essential elements used to create the garden are stone, the \"bones\" of the landscape; water, the life-giving force; and plants, the tapestry of the four seasons. Japanese garden designers feel that good stone composition is one of the most important elements in creating a well-designed garden. Secondary elements include pagodas, stone lanterns, water basins, arbors, and bridges. Japanese gardens are asymmetrical in design and reflect nature in idealized form. Traditionally, human scale is maintained throughout so that one always feels part of the environment and not overpowered by it. As Professor Tono wanted to incorporate native trees in the Portland Japanese Garden so that it would blend naturally with its environment, some of the plantings at the Garden are on a larger scale. (Wikipedia)",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "openLicense": true
  },
  {
    "id": "commons_4920472",
    "image": "images/commons_4920472.jpg",
    "month": 1,
    "day": 12,
    "location": "Strolling Pond Garden",
    "landmark": "Upper pond ",
    "point": {
      "lat": 45.5187888963979,
      "lon": -122.7088757813584,
      "name": "Upper pond ",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Adonelson",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden_-1.jpg",
    "caption": "Japanese Garden, Portland, Oregon, winter",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "openLicense": true
  },
  {
    "id": "official-001",
    "image": "images/official-001.jpg",
    "month": 9,
    "day": 14,
    "location": "Entry Garden",
    "landmark": "Entry Garden",
    "point": {
      "lat": 45.519046953560405,
      "lon": -122.70814451545805,
      "name": "Entry Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Entry Garden",
    "openLicense": false
  },
  {
    "id": "official-002",
    "image": "images/official-002.jpg",
    "month": 9,
    "day": 14,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.51889330427282,
      "lon": -122.70782200187315,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Flat Garden",
    "openLicense": false
  },
  {
    "id": "official-015",
    "image": "images/official-015.jpg",
    "month": 9,
    "day": 14,
    "location": "Tea Garden",
    "landmark": "Tea Garden",
    "point": {
      "lat": 45.518382957188194,
      "lon": -122.70929158891924,
      "name": "Tea Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Tea Garden",
    "openLicense": false
  },
  {
    "id": "official-026",
    "image": "images/official-026.jpg",
    "month": 11,
    "day": 6,
    "location": "Entry Garden",
    "landmark": "Entry Garden",
    "point": {
      "lat": 45.51939287051856,
      "lon": -122.70736293741338,
      "name": "Entry Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Entry Garden",
    "openLicense": false
  },
  {
    "id": "official-027",
    "image": "images/official-027.jpg",
    "month": 10,
    "day": 25,
    "location": "Entry Garden",
    "landmark": "Entry Garden",
    "point": {
      "lat": 45.519076245968165,
      "lon": -122.70792132534524,
      "name": "Entry Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Entry Garden",
    "openLicense": false
  },
  {
    "id": "official-028",
    "image": "images/official-028.jpg",
    "month": 11,
    "day": 8,
    "location": "Entry Garden",
    "landmark": "Entry Garden",
    "point": {
      "lat": 45.51909715911871,
      "lon": -122.70797181277273,
      "name": "Entry Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Entry Garden",
    "openLicense": false
  },
  {
    "id": "official-030",
    "image": "images/official-030.jpg",
    "month": 11,
    "day": 7,
    "location": "Entry Garden",
    "landmark": "Entry Garden",
    "point": {
      "lat": 45.51908977906823,
      "lon": -122.70788579907048,
      "name": "Entry Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Entry Garden",
    "openLicense": false
  },
  {
    "id": "official-031",
    "image": "images/official-031.jpg",
    "month": 11,
    "day": 7,
    "location": "Strolling Pond Garden",
    "landmark": "Lower Pond",
    "point": {
      "lat": 45.51797335419761,
      "lon": -122.70891896329684,
      "name": "Lower Pond",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Strolling Pond Garden",
    "openLicense": false
  },
  {
    "id": "official-032",
    "image": "images/official-032.jpg",
    "month": 11,
    "day": 3,
    "location": "Strolling Pond Garden",
    "landmark": "Moon Bridge",
    "point": {
      "lat": 45.51838506071631,
      "lon": -122.70915884075882,
      "name": "Moon Bridge",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Strolling Pond Garden",
    "openLicense": false
  },
  {
    "id": "official-033",
    "image": "images/official-033.jpg",
    "month": 11,
    "day": 7,
    "location": "Tea Garden",
    "landmark": "Tea House",
    "point": {
      "lat": 45.51869739038622,
      "lon": -122.70911330708823,
      "name": "Tea House",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Tea House",
    "openLicense": false
  },
  {
    "id": "official-034",
    "image": "images/official-034.jpg",
    "month": 10,
    "day": 25,
    "location": "Strolling Pond Garden",
    "landmark": "Moon Bridge",
    "point": {
      "lat": 45.5185024057214,
      "lon": -122.70913534840788,
      "name": "Moon Bridge",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Roman Johnston",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Moon Bridge",
    "openLicense": false
  },
  {
    "id": "official-035",
    "image": "images/official-035.jpg",
    "month": 10,
    "day": 19,
    "location": "Strolling Pond Garden",
    "landmark": "Cherry Hill",
    "point": {
      "lat": 45.518070136663034,
      "lon": -122.70847776195438,
      "name": "Cherry Hill",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": null,
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Hill overlooking Heavenly Falls",
    "openLicense": false
  },
  {
    "id": "official-036",
    "image": "images/official-036.jpg",
    "month": 11,
    "day": 8,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.51799344344687,
      "lon": -122.70893827764128,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Heavenly Falls",
    "openLicense": false
  },
  {
    "id": "official-038",
    "image": "images/official-038.jpg",
    "month": 11,
    "day": 3,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.5184087961816,
      "lon": -122.70801864745567,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Flat Garden",
    "openLicense": false
  },
  {
    "id": "official-039",
    "image": "images/official-039.jpg",
    "month": 11,
    "day": 5,
    "location": "Flat Garden",
    "landmark": "Weeping Cherry",
    "point": {
      "lat": 45.51851411571345,
      "lon": -122.7077026136684,
      "name": "Weeping Cherry",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Flat Garden",
    "openLicense": false
  },
  {
    "id": "official-040",
    "image": "images/official-040.jpg",
    "month": 11,
    "day": 5,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.518793419072544,
      "lon": -122.70794706944835,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Flat Garden",
    "openLicense": false
  },
  {
    "id": "official-041",
    "image": "images/official-041.jpg",
    "month": 11,
    "day": 3,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.518762601541724,
      "lon": -122.70782322787608,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Flat Garden",
    "openLicense": false
  },
  {
    "id": "official-042",
    "image": "images/official-042.jpg",
    "month": 11,
    "day": 7,
    "location": "Flat Garden",
    "landmark": "Weeping Cherry",
    "point": {
      "lat": 45.51849318499805,
      "lon": -122.70764469580142,
      "name": "Weeping Cherry",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Flat Garden",
    "openLicense": false
  },
  {
    "id": "official-044",
    "image": "images/official-044.jpg",
    "month": 11,
    "day": 1,
    "location": "Strolling Pond Garden",
    "landmark": "\"The Tree.\"",
    "point": {
      "lat": 45.5187703322717,
      "lon": -122.7086977247026,
      "name": "\"The Tree.\"",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "\"The Tree.\"",
    "openLicense": false
  },
  {
    "id": "official-045",
    "image": "images/official-045.jpg",
    "month": 10,
    "day": 31,
    "location": "Strolling Pond Garden",
    "landmark": "\"The Tree.\"",
    "point": {
      "lat": 45.51876750995696,
      "lon": -122.70870890796449,
      "name": "\"The Tree.\"",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Hunter Chesnut",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "\"The Tree.\"",
    "openLicense": false
  },
  {
    "id": "official-046",
    "image": "images/official-046.jpg",
    "month": 11,
    "day": 8,
    "location": "Strolling Pond Garden",
    "landmark": "\"The Tree.\"",
    "point": {
      "lat": 45.51878572347226,
      "lon": -122.70872234288066,
      "name": "\"The Tree.\"",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "\"The Tree.\"",
    "openLicense": false
  },
  {
    "id": "official-048",
    "image": "images/official-048.jpg",
    "month": 11,
    "day": 7,
    "location": "Natural Garden",
    "landmark": "Natural Garden",
    "point": {
      "lat": 45.51817186253618,
      "lon": -122.7076605825276,
      "name": "Natural Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Portland Japanese Garden",
    "source": "https://japanesegarden.org/seasonal-trackers/fall-colors-tracker-2026/",
    "caption": "Natural Garden",
    "openLicense": false
  },
  {
    "id": "commons_160697457",
    "image": "images/commons_160697457.jpg",
    "month": 1,
    "day": 27,
    "location": "Flat Garden",
    "landmark": "Circle and gourd islands from Pavilion",
    "point": {
      "lat": 45.518780534568315,
      "lon": -122.70782255239939,
      "name": "Circle and gourd islands from Pavilion",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "stu_spivack",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden_-_4321502828.jpg",
    "caption": "Japanese Garden, Portland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_160697452",
    "image": "images/commons_160697452.jpg",
    "month": 1,
    "day": 27,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.518418262401184,
      "lon": -122.70762105333368,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "stu_spivack",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden_-_4321511718.jpg",
    "caption": "Japanese Garden, Portland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_160697480",
    "image": "images/commons_160697480.jpg",
    "month": 1,
    "day": 27,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.518001419535864,
      "lon": -122.7087124355627,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "stu_spivack",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden_-_4321435512.jpg",
    "caption": "Japanese Garden, Portland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_73618820",
    "image": "images/commons_73618820.jpg",
    "month": 7,
    "day": 17,
    "location": "Flat Garden",
    "landmark": "Gourd island and pruned pines",
    "point": {
      "lat": 45.51865970129363,
      "lon": -122.70779515710926,
      "name": "Gourd island and pruned pines",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "\nIlya Grigorik",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Gardens_Portland_(166780009).jpeg",
    "caption": "\n500px provided description: 5.5 acres of beautifully landscaped gardens.. a must visit park in Portland and a great place to unwind. [#park ,#japan ,#green ,#garden ,#oregon ,#portland ,#japanese garden ,#washington park]",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "openLicense": true
  },
  {
    "id": "commons_2498081",
    "image": "images/commons_2498081.jpg",
    "month": 6,
    "day": 6,
    "location": "Flat Garden",
    "landmark": "Circle and gourd islands from Pavilion",
    "point": {
      "lat": 45.51876349556518,
      "lon": -122.70782753102887,
      "name": "Circle and gourd islands from Pavilion",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Laurascudder",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_garden_dry_garden.jpg",
    "caption": "Dry garden at Portland Japanese Garden",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "openLicense": true
  },
  {
    "id": "commons_11094021",
    "image": "images/commons_11094021.jpg",
    "month": 7,
    "day": 31,
    "location": "Flat Garden",
    "landmark": "Close view of circle and gourd islands",
    "point": {
      "lat": 45.51867198969073,
      "lon": -122.70784554426301,
      "name": "Close view of circle and gourd islands",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Heather from Seattle, WA",
    "source": "https://commons.wikimedia.org/wiki/File:Rock_garden,_Portland_Japanese_Garden.jpg",
    "caption": "One of the Zen rock gardens in the Portland Japanese Garden.",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_2498031",
    "image": "images/commons_2498031.jpg",
    "month": 6,
    "day": 6,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.5183782,
      "lon": -122.70723676,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Laurascudder",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_gardens_zen_garden.jpg",
    "caption": "Dry zen garden at Portland Japanese Garden",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "openLicense": true
  },
  {
    "id": "commons_76252186",
    "image": "images/commons_76252186.jpg",
    "month": 7,
    "day": 21,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls and Lower Pond reflection",
    "point": {
      "lat": 45.517995301615976,
      "lon": -122.70874781172066,
      "name": "Heavenly Falls and Lower Pond reflection",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "\nShitij Bhargava",
    "source": "https://commons.wikimedia.org/wiki/File:Reflect_In_The_Garden_(119298783).jpeg",
    "caption": "\n500px provided description: Taken in the Portland Japanese Garden [#lake ,#water ,#reflection ,#beautiful ,#green ,#garden ,#waterfall ,#long exposure ,#japanese]",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "openLicense": true
  },
  {
    "id": "flickr_51394644119",
    "image": "images/flickr_51394644119.jpg",
    "month": 8,
    "day": 8,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.51799887770983,
      "lon": -122.70873875496672,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Brandon Olafsson",
    "source": "https://www.flickr.com/photos/168888063@N04/51394644119/",
    "caption": "A lush forest scene surrounding a waterfall that leads into a tranquil koi pond at the Japanese Garden in Portland, OR.",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "openLicense": true
  },
  {
    "id": "commons_124358413",
    "image": "images/commons_124358413.jpg",
    "month": 11,
    "day": 24,
    "location": "Area needs review",
    "landmark": "Path to Moon Bridge",
    "point": {
      "lat": 45.51836179867863,
      "lon": -122.7086718805216,
      "name": "Path to Moon Bridge",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "G. Lamar",
    "source": "https://commons.wikimedia.org/wiki/File:%22Be_Not_Afraid_of_Going_Slowly,_Be_Afraid_of_Standing_Still%22_(46181673152).jpg",
    "caption": "original flickr: \"Be Not Afraid of Going Slowly, Be Afraid of Standing Still\"\nOld Japanese Proverb\n\nPortland Japanese Garden",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_30715046",
    "image": "images/commons_30715046.jpg",
    "month": 9,
    "day": 22,
    "location": "Strolling Pond Garden",
    "landmark": "Upper Pond",
    "point": {
      "lat": 45.51875960399014,
      "lon": -122.70889637164679,
      "name": "Upper Pond",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Šarūnas Burdulis from USA",
    "source": "https://commons.wikimedia.org/wiki/File:In_Japanese_garden,_Portland_(4333296058).jpg",
    "caption": "In Japanese garden, Portland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_92405818",
    "image": "images/commons_92405818.jpg",
    "month": 11,
    "day": 4,
    "location": "Strolling Pond Garden",
    "landmark": "The Tree",
    "point": {
      "lat": 45.518776642993274,
      "lon": -122.70872964827177,
      "name": "The Tree",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Sasquatch I",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden,_Portland_Oregon_-_Flickr_-_Sasquatch_I.jpg",
    "caption": "Japanese Garden, Portland Oregon",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_71348628",
    "image": "images/commons_71348628.jpg",
    "month": 9,
    "day": 6,
    "location": "Flat Garden",
    "landmark": "Laceleaf maple",
    "point": {
      "lat": 45.51890550505151,
      "lon": -122.70766210856831,
      "name": "Laceleaf maple",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Carola Hornbach",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Maple_(232883841).jpeg",
    "caption": "500px provided description: Japanese Maple, Portland Japanese Garden [#leaves ,#tree ,#green ,#garden ,#japanese ,#bontanical]",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "openLicense": true
  },
  {
    "id": "commons_41790945",
    "image": "images/commons_41790945.jpg",
    "month": 5,
    "day": 14,
    "location": "Strolling Pond Garden",
    "landmark": "Koi in Lower Pond",
    "point": {
      "lat": 45.518087964574974,
      "lon": -122.70897670597857,
      "name": "Koi in Lower Pond",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Tony Webster from Portland, Oregon",
    "source": "https://commons.wikimedia.org/wiki/File:Koi_Pond_-_Portland_Japanese_Garden_(18206438211).jpg",
    "caption": "Portland Japanese Garden",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_23044881",
    "image": "images/commons_23044881.jpg",
    "month": 3,
    "day": 9,
    "location": "Area needs review",
    "landmark": "Ducks!",
    "point": {
      "lat": 45.518206308718185,
      "lon": -122.70897015117151,
      "name": "Ducks!",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Tony Herrig",
    "source": "https://commons.wikimedia.org/wiki/File:Mallard_Ducks,_Japanese_Gardens,_Portland,_Oregon.JPG",
    "caption": "Two Mallard Anas platyrhynchos resting at the main pool at the Japanese Gardens in Portland, Oregon.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "openLicense": true
  },
  {
    "id": "commons_41791161",
    "image": "images/commons_41791161.jpg",
    "month": 5,
    "day": 14,
    "location": "Flat Garden",
    "landmark": "Circle island",
    "point": {
      "lat": 45.518681140291896,
      "lon": -122.70780641538059,
      "name": "Circle island",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Tony Webster from Portland, Oregon",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_(17834386035).jpg",
    "caption": "Portland Japanese Garden",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_46133857",
    "image": "images/commons_46133857.jpg",
    "month": 5,
    "day": 14,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.51800266417021,
      "lon": -122.70873465196969,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Tony Webster from Washington, DC",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_(23552294535).jpg",
    "caption": "Portland, Oregon",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_47643776",
    "image": "images/commons_47643776.jpg",
    "month": 5,
    "day": 14,
    "location": "Flat Garden",
    "landmark": "Moss border and maples",
    "point": {
      "lat": 45.51879808199154,
      "lon": -122.70802167466452,
      "name": "Moss border and maples",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Tony Webster from San Francisco, California",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_Oregon_(25732059885).jpg",
    "caption": "Portland, Oregon",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_58840965",
    "image": "images/commons_58840965.jpg",
    "month": 5,
    "day": 4,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.51800606502724,
      "lon": -122.70876247254182,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Delicious",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_panoramio.jpg",
    "caption": "Portland Japanese Garden",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "openLicense": true
  },
  {
    "id": "commons_160720809",
    "image": "images/commons_160720809.jpg",
    "month": 5,
    "day": 14,
    "location": "Strolling Pond Garden",
    "landmark": "Maples",
    "point": {
      "lat": 45.51837773329177,
      "lon": -122.70884898653551,
      "name": "Maples",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Tony Webster",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_Trees_(17285721683).jpg",
    "caption": "Portland Japanese Garden - Trees",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_134014614",
    "image": "images/commons_134014614.jpg",
    "month": 7,
    "day": 7,
    "location": "Cultural Village",
    "landmark": "Bamboo Allee",
    "point": {
      "lat": 45.518916022966536,
      "lon": -122.70847783706176,
      "name": "Bamboo Allee",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Steven Baltakatei Sandoval",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_Tanabata_tanzaku.jpg",
    "caption": "A photograph of tanzaku (colored strips of paper with wishes written on them) hanging on bamboo trees growing within the Portland Japanese Garden as part of a Tanabata celebration held on 2023-07-07. Photograph taken on 2022-07-07T11:36:53-07.\nOrig name: PXL_20220707_183653289.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_85635414",
    "image": "images/commons_85635414.jpg",
    "month": 4,
    "day": 13,
    "location": "Strolling Pond Garden",
    "landmark": "Sapporo Pagoda",
    "point": {
      "lat": 45.5182907,
      "lon": -122.7085868,
      "name": "Sapporo Pagoda",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Paul Trafford",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_scene_(8656097497).jpg",
    "caption": "Portland, Oregon, in spring.",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_85635402",
    "image": "images/commons_85635402.jpg",
    "month": 4,
    "day": 13,
    "location": "Tea Garden",
    "landmark": "Tea Garden",
    "point": {
      "lat": 45.51843826396342,
      "lon": -122.70929521659534,
      "name": "Tea Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Paul Trafford",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_scene_(8657201546).jpg",
    "caption": "Portland, Oregon, in spring.",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_76194888",
    "image": "images/commons_76194888.jpg",
    "month": 11,
    "day": 26,
    "location": "Strolling Pond Garden",
    "landmark": "Lower Pond Waterfall",
    "point": {
      "lat": 45.51816488558531,
      "lon": -122.70908343491965,
      "name": "Lower Pond Waterfall",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Jeff Gunn from Atlanta, USA",
    "source": "https://commons.wikimedia.org/wiki/File:Portland,_OR_(8237613273).jpg",
    "caption": "Portland Japanese Garden",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_134156444",
    "image": "images/commons_134156444.jpg",
    "month": 7,
    "day": 7,
    "location": "Cultural Village",
    "landmark": "Bamboo Allee",
    "point": {
      "lat": 45.51892619033928,
      "lon": -122.70843080222305,
      "name": "Bamboo Allee",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Steven Baltakatei Sandoval",
    "source": "https://commons.wikimedia.org/wiki/File:Tanabata_tanzaku.jpg",
    "caption": "Tanabata tanzaku hanging on bamboo trees planted in the Crumpacker Family Bamboo Allee located within the Portland Japanese Garden. See this gallery for more photos from this event at this location and time. Photograph taken on 2023-07-07T17:19:06-07.\nOrig name: 20230708T001906+0000_DSC00359.JPG",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_163154710",
    "image": "images/commons_163154710.jpg",
    "month": 11,
    "day": 6,
    "location": "Entry Garden",
    "landmark": "Antique Gate",
    "point": {
      "lat": 45.519409120681495,
      "lon": -122.70767354212282,
      "name": "Antique Gate",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "WLernerPJG",
    "source": "https://commons.wikimedia.org/wiki/File:The_Entry_Garden_at_Portland_Japanese_Garden.jpg",
    "caption": "The Entry Garden at Portland Japanese Garden",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_124358407",
    "image": "images/commons_124358407.jpg",
    "month": 11,
    "day": 24,
    "location": "Strolling Pond Garden",
    "landmark": "Upper Pond",
    "point": {
      "lat": 45.5187703322717,
      "lon": -122.70870838250669,
      "name": "Upper Pond",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "G. Lamar",
    "source": "https://commons.wikimedia.org/wiki/File:The_Lagoon_(45514327354).jpg",
    "caption": "Japanese Gardens Portand Oregon",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_124358402",
    "image": "images/commons_124358402.jpg",
    "month": 11,
    "day": 24,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.51879476882155,
      "lon": -122.70785272460574,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "G. Lamar",
    "source": "https://commons.wikimedia.org/wiki/File:The_Zen_Garden_(45514613074).jpg",
    "caption": "Portland Japanese Garden",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_16740263",
    "image": "images/commons_16740263.jpg",
    "month": 7,
    "day": 10,
    "location": "Flat Garden",
    "landmark": "Mt. Hood Overlook",
    "point": {
      "lat": 45.518741022299096,
      "lon": -122.707499638503,
      "name": "Mt. Hood Overlook",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Visitor7",
    "source": "https://commons.wikimedia.org/wiki/File:View_from_the_Japanese_Garden_(Portland,_Oregon).jpg",
    "caption": "View from the Japanese Garden (Portland, Oregon)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "openLicense": true
  },
  {
    "id": "commons_71795466",
    "image": "images/commons_71795466.jpg",
    "month": 11,
    "day": 1,
    "location": "Cultural Village",
    "landmark": "Bonsai Terrace",
    "point": {
      "lat": 45.518893093906286,
      "lon": -122.70862949920617,
      "name": "Bonsai Terrace",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Bonsai_collection_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08157.jpg",
    "caption": "Bonsai collection - Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796409",
    "image": "images/commons_71796409.jpg",
    "month": 11,
    "day": 1,
    "location": "Flat Garden",
    "landmark": "Flat Garden - Portland Japanese Garden - Portland, Oregon - DSC08354.jpg",
    "point": {
      "lat": 45.51867826541982,
      "lon": -122.70780291285081,
      "name": "Flat Garden - Portland Japanese Garden - Portland, Oregon - DSC08354.jpg",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Flat_Garden_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08354.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_163154205",
    "image": "images/commons_163154205.jpg",
    "month": 10,
    "day": 29,
    "location": "Flat Garden",
    "landmark": "Flat Garden in Portland Japanese Garden.jpg",
    "point": {
      "lat": 45.51856111321642,
      "lon": -122.70777586773532,
      "name": "Flat Garden in Portland Japanese Garden.jpg",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "WLernerPJG",
    "source": "https://commons.wikimedia.org/wiki/File:Flat_Garden_in_Portland_Japanese_Garden.jpg",
    "caption": "The Flat Garden of Portland Japanese Garden.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_71796295",
    "image": "images/commons_71796295.jpg",
    "month": 11,
    "day": 1,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.51800727453189,
      "lon": -122.70878691563256,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Heavenly_Falls_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08312.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796294",
    "image": "images/commons_71796294.jpg",
    "month": 11,
    "day": 1,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.51800028015339,
      "lon": -122.70895656613854,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Heavenly_Falls_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08320.jpg",
    "caption": "Heavenly Falls, Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796066",
    "image": "images/commons_71796066.jpg",
    "month": 11,
    "day": 1,
    "location": "Strolling Pond Garden",
    "landmark": "Upper Pond",
    "point": {
      "lat": 45.51836271012972,
      "lon": -122.70883990481107,
      "name": "Upper Pond",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Pond_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08269.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_40651615",
    "image": "images/commons_40651615.jpg",
    "month": 9,
    "day": 10,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.518050205222984,
      "lon": -122.70883485107423,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Jon Roberts from Austin TX, USA",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_(2013-09-10_14.30.58_by_Jon_Roberts).jpg",
    "caption": "Japanese garden",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_64289788",
    "image": "images/commons_64289788.jpg",
    "month": 10,
    "day": 10,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.51799849210646,
      "lon": -122.70875571757902,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "John Fowler from Placitas, NM, USA",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_(37690912536).jpg",
    "caption": "Portland Japanese Garden",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "openLicense": true
  },
  {
    "id": "commons_118421018",
    "image": "images/commons_118421018.jpg",
    "month": 10,
    "day": 29,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.51799298772132,
      "lon": -122.70874956298555,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "King of Hearts",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_October_2019_005.jpg",
    "caption": "Heavenly Falls, Portland Japanese Garden, Portland, Oregon.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_118421025",
    "image": "images/commons_118421025.jpg",
    "month": 10,
    "day": 29,
    "location": "Strolling Pond Garden",
    "landmark": "Lower Pond Falls",
    "point": {
      "lat": 45.518142061708325,
      "lon": -122.70907487865301,
      "name": "Lower Pond Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "King of Hearts",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_October_2019_006.jpg",
    "caption": "Pond, Portland Japanese Garden, Portland, Oregon.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_118421036",
    "image": "images/commons_118421036.jpg",
    "month": 10,
    "day": 29,
    "location": "Natural Garden",
    "landmark": "Natural Garden",
    "point": {
      "lat": 45.51807408093263,
      "lon": -122.70737014262869,
      "name": "Natural Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "King of Hearts",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_October_2019_009.jpg",
    "caption": "Pond, Portland Japanese Garden, Portland, Oregon.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_12338118",
    "image": "images/commons_12338118.jpg",
    "month": 10,
    "day": 22,
    "location": "Strolling Pond Garden",
    "landmark": "Upper Pond and Moon Bridge",
    "point": {
      "lat": 45.51876714178122,
      "lon": -122.7088094573416,
      "name": "Upper Pond and Moon Bridge",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Melissa Wilmot",
    "source": "https://commons.wikimedia.org/wiki/File:Strolling_Pond_Garden.jpg",
    "caption": "Strolling Pond Garden at the Portland Japanese Garden.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "openLicense": true
  },
  {
    "id": "commons_71796063",
    "image": "images/commons_71796063.jpg",
    "month": 11,
    "day": 1,
    "location": "Strolling Pond Garden",
    "landmark": "Sapporo Pagoda",
    "point": {
      "lat": 45.518344952477186,
      "lon": -122.70860085304052,
      "name": "Sapporo Pagoda",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Pagoda_lantern_and_stones-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08252.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71795898",
    "image": "images/commons_71795898.jpg",
    "month": 11,
    "day": 1,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.51842790372037,
      "lon": -122.70760859412785,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Sand_and_Stone_Garden_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08222.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796415",
    "image": "images/commons_71796415.jpg",
    "month": 11,
    "day": 1,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.5183782,
      "lon": -122.70723676,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Sand_and_Stone_Garden_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08344.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796417",
    "image": "images/commons_71796417.jpg",
    "month": 11,
    "day": 1,
    "location": "Strolling Pond Garden",
    "landmark": "Zig Zag Bridge",
    "point": {
      "lat": 45.518034393289355,
      "lon": -122.70884633456974,
      "name": "Zig Zag Bridge",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Zig-zag_Bridge_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08315.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796061",
    "image": "images/commons_71796061.jpg",
    "month": 11,
    "day": 1,
    "location": "Strolling Pond Garden",
    "landmark": "Moon Bridge",
    "point": {
      "lat": 45.51837533171009,
      "lon": -122.70886489833012,
      "name": "Moon Bridge",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Bridge_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08265.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71795127",
    "image": "images/commons_71795127.jpg",
    "month": 11,
    "day": 1,
    "location": "Entry Garden",
    "landmark": "Antique Gate",
    "point": {
      "lat": 45.519386191621244,
      "lon": -122.70771704936331,
      "name": "Antique Gate",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Entry_gate_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08118.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71795126",
    "image": "images/commons_71795126.jpg",
    "month": 11,
    "day": 1,
    "location": "Cultural Village",
    "landmark": "Garden House and Fukuta Concierge Office",
    "point": {
      "lat": 45.51902724998312,
      "lon": -122.70881646249909,
      "name": "Garden House and Fukuta Concierge Office",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Garden_House_%26_Fukuta_Concierge_Office_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08144.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71795568",
    "image": "images/commons_71795568.jpg",
    "month": 11,
    "day": 1,
    "location": "Cultural Village",
    "landmark": "Bamboo Allee",
    "point": {
      "lat": 45.518916373577426,
      "lon": -122.7085241462869,
      "name": "Bamboo Allee",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Inner_gate_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08166.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796411",
    "image": "images/commons_71796411.jpg",
    "month": 11,
    "day": 1,
    "location": "Natural Garden",
    "landmark": "Moon Gate",
    "point": {
      "lat": 45.518138415492295,
      "lon": -122.70819485267079,
      "name": "Moon Gate",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Inner_gate_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08332.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796410",
    "image": "images/commons_71796410.jpg",
    "month": 11,
    "day": 1,
    "location": "Strolling Pond Garden",
    "landmark": "Sapporo Pagoda",
    "point": {
      "lat": 45.51832228627219,
      "lon": -122.70853703077476,
      "name": "Sapporo Pagoda",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Pagoda_lantern_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08327.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71795569",
    "image": "images/commons_71795569.jpg",
    "month": 11,
    "day": 1,
    "location": "Flat Garden",
    "landmark": "Pavilion Gallery ",
    "point": {
      "lat": 45.518821274044264,
      "lon": -122.70754209482787,
      "name": "Pavilion Gallery ",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Pavilion_Gallery_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08195.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796216",
    "image": "images/commons_71796216.jpg",
    "month": 11,
    "day": 1,
    "location": "Tea Garden",
    "landmark": "Tea Garden Shelter",
    "point": {
      "lat": 45.518292187528,
      "lon": -122.70916221824021,
      "name": "Tea Garden Shelter",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Rain_shelter_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08300.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796215",
    "image": "images/commons_71796215.jpg",
    "month": 11,
    "day": 1,
    "location": "Tea Garden",
    "landmark": "Tea garden ",
    "point": {
      "lat": 45.518535169108354,
      "lon": -122.7091908393864,
      "name": "Tea garden ",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Tea_garden_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08289.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796217",
    "image": "images/commons_71796217.jpg",
    "month": 11,
    "day": 1,
    "location": "Tea Garden",
    "landmark": "Tea garden Basin",
    "point": {
      "lat": 45.5184465906633,
      "lon": -122.70926574483619,
      "name": "Tea garden Basin",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Tea_garden_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08296.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796220",
    "image": "images/commons_71796220.jpg",
    "month": 11,
    "day": 1,
    "location": "Tea Garden",
    "landmark": "Tea garden fence ",
    "point": {
      "lat": 45.51842892056057,
      "lon": -122.70930875163833,
      "name": "Tea garden fence ",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Tea_garden_fence_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08298.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796218",
    "image": "images/commons_71796218.jpg",
    "month": 11,
    "day": 1,
    "location": "Tea Garden",
    "landmark": "Teahouse Gate",
    "point": {
      "lat": 45.518708276476985,
      "lon": -122.70899584513776,
      "name": "Teahouse Gate",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Tea_garden_gate_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08278.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796219",
    "image": "images/commons_71796219.jpg",
    "month": 11,
    "day": 1,
    "location": "Tea Garden",
    "landmark": "Tea Garden Gate ",
    "point": {
      "lat": 45.518238055264945,
      "lon": -122.70911080523928,
      "name": "Tea Garden Gate ",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Tea_garden_gate_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08301.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_71796221",
    "image": "images/commons_71796221.jpg",
    "month": 11,
    "day": 1,
    "location": "Tea Garden",
    "landmark": "Tea garden gate and stone ",
    "point": {
      "lat": 45.51818679801119,
      "lon": -122.70904963493928,
      "name": "Tea garden gate and stone ",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Daderot",
    "source": "https://commons.wikimedia.org/wiki/File:Tea_garden_gate_and_stone_-_Portland_Japanese_Garden_-_Portland,_Oregon_-_DSC08304.jpg",
    "caption": "Portland Japanese Garden - Portland, Oregon, USA.",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034254",
    "image": "images/commons_165034254.jpg",
    "month": 10,
    "day": 15,
    "location": "Strolling Pond Garden",
    "landmark": "Upper Pond",
    "point": {
      "lat": 45.518766721048145,
      "lon": -122.70881786349142,
      "name": "Upper Pond",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_002.jpg",
    "caption": "The Strolling Pond Garden in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034259",
    "image": "images/commons_165034259.jpg",
    "month": 10,
    "day": 15,
    "location": "Strolling Pond Garden",
    "landmark": "Upper Pond",
    "point": {
      "lat": 45.518774960061,
      "lon": -122.70881083336342,
      "name": "Upper Pond",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_005.jpg",
    "caption": "The Strolling Pond Garden in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034266",
    "image": "images/commons_165034266.jpg",
    "month": 10,
    "day": 15,
    "location": "Strolling Pond Garden",
    "landmark": "Sapporo Pagoda",
    "point": {
      "lat": 45.51834440906461,
      "lon": -122.70857483377222,
      "name": "Sapporo Pagoda",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_012.jpg",
    "caption": "The Sapporo Pagoda Lantern in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034277",
    "image": "images/commons_165034277.jpg",
    "month": 10,
    "day": 15,
    "location": "Strolling Pond Garden",
    "landmark": "Heavenly Falls",
    "point": {
      "lat": 45.518021263426114,
      "lon": -122.70879337045966,
      "name": "Heavenly Falls",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_019.jpg",
    "caption": "Heavenly Falls in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034286",
    "image": "images/commons_165034286.jpg",
    "month": 10,
    "day": 15,
    "location": "Natural Garden",
    "landmark": "Moon Gate",
    "point": {
      "lat": 45.51814262268575,
      "lon": -122.70819317641534,
      "name": "Moon Gate",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_025.jpg",
    "caption": "Moon Gate in the Portland Japanese Garden, which leads to the Natural Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034293",
    "image": "images/commons_165034293.jpg",
    "month": 10,
    "day": 15,
    "location": "Natural Garden",
    "landmark": "Natural Garden",
    "point": {
      "lat": 45.518130229036764,
      "lon": -122.70788374757197,
      "name": "Natural Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_026.jpg",
    "caption": "The Natural Garden in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034252",
    "image": "images/commons_165034252.jpg",
    "month": 10,
    "day": 15,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.5183782,
      "lon": -122.70723676,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_030.jpg",
    "caption": "The Sand and Stone Garden in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034493",
    "image": "images/commons_165034493.jpg",
    "month": 10,
    "day": 15,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.5183782,
      "lon": -122.70723676,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_031.jpg",
    "caption": "The Sand and Stone Garden in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034499",
    "image": "images/commons_165034499.jpg",
    "month": 10,
    "day": 15,
    "location": "Flat Garden",
    "landmark": "Weeping Cherry",
    "point": {
      "lat": 45.51851348461385,
      "lon": -122.70769450755635,
      "name": "Weeping Cherry",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_036.jpg",
    "caption": "The Flat Garden in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034508",
    "image": "images/commons_165034508.jpg",
    "month": 10,
    "day": 15,
    "location": "Flat Garden",
    "landmark": "Gourd Island",
    "point": {
      "lat": 45.51868547016486,
      "lon": -122.70780531452397,
      "name": "Gourd Island",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_040.jpg",
    "caption": "The Flat Garden in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034538",
    "image": "images/commons_165034538.jpg",
    "month": 10,
    "day": 15,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.51879026371176,
      "lon": -122.70802335091997,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_049.jpg",
    "caption": "The Flat Garden in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_165034545",
    "image": "images/commons_165034545.jpg",
    "month": 10,
    "day": 15,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.518683138705356,
      "lon": -122.70814499077899,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "Vulturesong",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_-_HCP_-_October_15,_2022_-_050.jpg",
    "caption": "The Flat Garden in the Portland Japanese Garden",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "openLicense": true
  },
  {
    "id": "commons_160697472",
    "image": "images/commons_160697472.jpg",
    "month": 1,
    "day": 27,
    "location": "Flat Garden",
    "landmark": "Poetry Stone",
    "point": {
      "lat": 45.51838846157333,
      "lon": -122.7077052154973,
      "name": "Poetry Stone",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "stu_spivack",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden_(Portland).jpg",
    "caption": "Japanese Garden, Portland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_160697487",
    "image": "images/commons_160697487.jpg",
    "month": 1,
    "day": 27,
    "location": "Strolling Pond Garden",
    "landmark": "Upstream of Lower Pond",
    "point": {
      "lat": 45.51819375725999,
      "lon": -122.70894137985955,
      "name": "Upstream of Lower Pond",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "stu_spivack",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden_-_4320685549.jpg",
    "caption": "Japanese Garden, Portland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_160697450",
    "image": "images/commons_160697450.jpg",
    "month": 1,
    "day": 27,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.51877422384675,
      "lon": -122.70783078346189,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "stu_spivack",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden_-_4320772181.jpg",
    "caption": "Japanese Garden, Portland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_160697469",
    "image": "images/commons_160697469.jpg",
    "month": 1,
    "day": 27,
    "location": "Sand and Stone Garden",
    "landmark": "Sand and Stone Garden",
    "point": {
      "lat": 45.5183782,
      "lon": -122.70723676,
      "name": "Sand and Stone Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "stu_spivack",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden_-_4321472716.jpg",
    "caption": "Japanese Garden, Portland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_160697458",
    "image": "images/commons_160697458.jpg",
    "month": 1,
    "day": 27,
    "location": "Natural Garden",
    "landmark": "Water Basin",
    "point": {
      "lat": 45.518093188471404,
      "lon": -122.7076278082965,
      "name": "Water Basin",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "stu_spivack",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Garden_-_4321498664.jpg",
    "caption": "Japanese Garden, Portland",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "openLicense": true
  },
  {
    "id": "commons_118420977",
    "image": "images/commons_118420977.jpg",
    "month": 10,
    "day": 29,
    "location": "Cultural Village",
    "landmark": "Castle wall",
    "point": {
      "lat": 45.519150274610176,
      "lon": -122.70909169105059,
      "name": "Castle wall",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "King of Hearts",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_October_2019_001.jpg",
    "caption": "Zagunis Castle Wall, Portland Japanese Garden, Portland, Oregon.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_118420984",
    "image": "images/commons_118420984.jpg",
    "month": 10,
    "day": 29,
    "location": "Cultural Village",
    "landmark": "Learning Center",
    "point": {
      "lat": 45.51905161654802,
      "lon": -122.70879269488505,
      "name": "Learning Center",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "King of Hearts",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_October_2019_002.jpg",
    "caption": "Jordan Schnitzer Japanese Arts Learning Center, Portland Japanese Garden, Portland, Oregon.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_118421028",
    "image": "images/commons_118421028.jpg",
    "month": 10,
    "day": 29,
    "location": "Strolling Pond Garden",
    "landmark": "Moon Bridge",
    "point": {
      "lat": 45.518324495052184,
      "lon": -122.70911488326581,
      "name": "Moon Bridge",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "King of Hearts",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_October_2019_007.jpg",
    "caption": "Moon Bridge, Portland Japanese Garden, Portland, Oregon.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_118420993",
    "image": "images/commons_118420993.jpg",
    "month": 10,
    "day": 29,
    "location": "Flat Garden",
    "landmark": "Flat Garden",
    "point": {
      "lat": 45.518699301249875,
      "lon": -122.70781149408795,
      "name": "Flat Garden",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "King of Hearts",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_October_2019_003.jpg",
    "caption": "Portland Japanese Garden, Portland, Oregon.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_118421032",
    "image": "images/commons_118421032.jpg",
    "month": 10,
    "day": 29,
    "location": "Flat Garden",
    "landmark": "Maple",
    "point": {
      "lat": 45.5189028580422,
      "lon": -122.70809375286537,
      "name": "Maple",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "King of Hearts",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_October_2019_008.jpg",
    "caption": "Portland Japanese Garden, Portland, Oregon.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  },
  {
    "id": "commons_118421039",
    "image": "images/commons_118421039.jpg",
    "month": 10,
    "day": 29,
    "location": "Flat Garden",
    "landmark": "Mt Hood Overlook",
    "point": {
      "lat": 45.51878170908049,
      "lon": -122.70749098206056,
      "name": "Mt Hood Overlook",
      "status": "reviewed",
      "basis": "Landmark confirmed in your saved review."
    },
    "credit": "King of Hearts",
    "source": "https://commons.wikimedia.org/wiki/File:Portland_Japanese_Garden_October_2019_010.jpg",
    "caption": "Mount Hood Overlook, Portland Japanese Garden, Portland, Oregon.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "openLicense": true
  }
];
