(() => {
  const $=id=>document.getElementById(id),R=window.GardenReview,all=window.GARDEN_PHOTOS;
  const names=['January','February','March','April','May','June','July','August','September','October','November','December'];
  let list=all,index=0,pin=null,dirty=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const safe=u=>{try{const a=new URL(u);return /^https?:$/.test(a.protocol)?a.href:'#';}catch{return '#';}};
  const status=s=>$('reviewStatus').textContent=s;
  const map=GardenMap.create($('reviewMap'),{onChange:p=>{pin=p;dirty=true;$('approvePin').checked=false;coords();}});
  $('reviewMonth').innerHTML='<option value="">Unknown</option>'+names.map((n,i)=>`<option value="${i+1}">${n}</option>`).join('');
  function coords(){$('reviewCoords').textContent=pin?`${pin.lat.toFixed(6)}, ${pin.lon.toFixed(6)} · position selected`:'No pin placed.';}
  function render(){const p=list[index];if(!p){$('reviewGrid').hidden=true;status('No photos match this filter. Choose another filter.');$('reviewForm').hidden=true;return;}$('reviewForm').hidden=false;$('reviewGrid').hidden=false;const e=R.get(p.id),r=R.resolve(p);
    $('reviewPhoto').value=p.id;$('reviewImage').src=p.image;$('reviewImage').alt=p.caption||'Garden photograph for review';
    $('reviewCredit').innerHTML=`Photo: ${esc(p.credit)} · ${esc(p.id)}<br><a target="_blank" rel="noopener" href="${esc(safe(p.source))}">Original source ↗</a>${p.licenseUrl?`<a href="${esc(safe(p.licenseUrl))}" target="_blank" rel="noopener">${esc(p.license)}</a>`:''}`;
    $('reviewEvidence').innerHTML=`<p><strong>Capture date:</strong> ${p.month?names[p.month-1]+' '+p.day:'Not established'}</p><p>${esc(p.dateEvidence||'See the original source for the recorded capture date.')}</p><p><strong>Area:</strong> ${esc(p.location||'Needs review')}</p><p>${esc(p.locationEvidence||'Area is based on source description or landmark matching; check it against the photograph.')}</p><p><strong>Map reference:</strong> ${esc(p.point?.basis||'No reliable landmark coordinate was available. Place and confirm one using your knowledge of the Garden.')}</p>`;
    $('reviewMonth').value=e.month??p.month??'';$('reviewDay').value=e.day??p.day??'';$('reviewArea').value=e.location||p.location||'';$('reviewLandmark').value=e.landmark||p.point?.name||p.landmark||'';$('reviewNotes').value=e.note||'';$('approveDate').checked=e.dateApproved===true;$('approvePin').checked=e.pointApproved===true;$('excludePhoto').checked=e.excluded===true;
    pin=e.point||p.point||null;map?.reset();map?.setPin(pin);coords();$('pinStatus').textContent=e.pointApproved?'Confirmed by you':p.point?'Source landmark location · unreviewed':'Pin needed';dirty=false;
  }
  function filtered(){const f=$('reviewFilter').value;list=all.filter(p=>{const r=R.resolve(p),e=R.get(p.id);return f==='all'||f==='pin'&&!e.pointApproved||f==='date'&&!r.dateReady||f==='map'&&!!r.point||f==='reviewed'&&Object.keys(e).length>0||f==='excluded'&&r.excluded;});index=0;$('reviewPhoto').innerHTML=list.map((p,i)=>`<option value="${esc(p.id)}">${i+1}. ${esc(p.location||'Area needs review')} · ${p.month?names[p.month-1]+' '+p.day:'Date needed'} · ${esc(p.id)}</option>`).join('');render();}
  function save(){const p=list[index];if(!p)return false;const m=+$('reviewMonth').value,d=+$('reviewDay').value;try{R.save(p.id,{...(m&&d?{month:m,day:d}:{}),point:pin,location:$('reviewArea').value,landmark:$('reviewLandmark').value,dateApproved:$('approveDate').checked,pointApproved:$('approvePin').checked,excluded:$('excludePhoto').checked,note:$('reviewNotes').value});dirty=false;status(R.storageOK?'Saved in this browser. Export your reviews to keep a portable backup.':'Saved for this session only. Browser storage is unavailable—export your reviews now.');$('pinStatus').textContent=$('approvePin').checked?'Confirmed by you':pin?'Pin saved · needs confirmation':'Pin needed';return true;}catch(e){status(e.message);return false;}}
  function leave(){return !dirty||save();}
  $('reviewForm').addEventListener('input',()=>dirty=true);$('reviewForm').addEventListener('submit',e=>{e.preventDefault();save();});
  $('reviewPhoto').addEventListener('change',e=>{if(!leave()){e.target.value=list[index].id;return;}index=list.findIndex(p=>p.id===e.target.value);render();});
  $('reviewFilter').addEventListener('change',()=>{if(leave())filtered();});
  $('previousReview').addEventListener('click',()=>{if(list.length&&leave()){index=(index-1+list.length)%list.length;render();}});$('nextReview').addEventListener('click',()=>{if(list.length&&leave()){index=(index+1)%list.length;render();}});
  $('resetReview').addEventListener('click',()=>{if(list[index]){R.remove(list[index].id);render();status('Local changes for this photo were reset to the saved site defaults.');}});
  $('exportReviews').addEventListener('click',()=>{if(!leave())return;const blob=new Blob([JSON.stringify(R.export(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='garden-photo-reviews.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Review backup exported. Import it to use your corrections in another browser or copy.');});
  $('importReviews').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('Review file is too large.');const count=R.import(JSON.parse(await f.text()));filtered();status(`Imported ${count} photo reviews. ${R.storageOK?'Saved in this browser.':'Export again before closing; browser storage is unavailable.'}`);}catch(err){status('Import failed: '+err.message);}e.target.value='';});
  window.addEventListener('beforeunload',()=>{if(dirty)save();});filtered();const requested=new URLSearchParams(location.search).get('photo');if(requested){const i=list.findIndex(p=>p.id===requested);if(i>=0){index=i;render();}}
})();
